enum TextSizes { SMALL, MEDIUM, LARGE }

enum OrderStatus { PROCESSING, SHIPPED, DELIVERED, CANCELLED }

enum PaymentMethod {
  PAYPAL,
  VISA,
  APPLE_PAY,
  GOOGLE_PAY,
  MASTER_CARD,
  CREDIT_CARD
}
