// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCecKa7Z31FB9fsU2t4zJRpyjCXsnAFI',
    appId: '1:1091430793832:web:42f21c7b07d27278a431dd',
    messagingSenderId: '1091430793832',
    projectId: 'qaf-store',
    authDomain: 'qaf-store.firebaseapp.com',
    storageBucket: 'qaf-store.firebasestorage.app',
    measurementId: 'G-FPE0H60GS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GCuaafFymFMiliMMT9qdRaERwuib388',
    appId: '1:1091430793832:android:814e9a1d4a1c0a03a431dd',
    messagingSenderId: '1091430793832',
    projectId: 'qaf-store',
    storageBucket: 'qaf-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-LNZH8rjzhsKGNzMeAcs0wqwoJkO0EJw',
    appId: '1:1091430793832:ios:feb377d52f8d19eca431dd',
    messagingSenderId: '1091430793832',
    projectId: 'qaf-store',
    storageBucket: 'qaf-store.firebasestorage.app',
    iosBundleId: 'com.example.qafStore',
  );

}